# Generated by Django 5.2 on 2025-04-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
