# Generated by Django 5.2 on 2025-04-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_chat_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='session_id',
            field=models.CharField(max_length=255),
        ),
    ]
